### ISSUE TITLE
Fix documentation for interactions

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/Novus#28]
Notably: the docstring for "options" is wrong, but go through everything anyway before releasing modals.

**Comment by 4Kaylum** [comment]
I think I've done this on master - @schlopp could you weigh in on what else you think needs documenting/an example?

**Comment by schlopp** [comment]
> I think I've done this on master - @schlopp could you weigh in on what else you think needs documenting/an example?

When I encounter anything I find lacking in documentation, I'll tell you. Can't think of anything off the top of my head.
